project_id = "prcrvuzncffsblsxblim"

[functions.send-sms]
verify_jwt = false

[functions.send-booking-sms]
verify_jwt = false

[functions.send-booking-confirmation]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.notify-workers]
verify_jwt = false

[functions.send-review-request]
verify_jwt = false

[functions.twilio-webhook]
verify_jwt = false

[functions.send-reminder-sms]
verify_jwt = false

[functions.manage-booking]
verify_jwt = false

[functions.create-booking]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.create-deposit-checkout]
verify_jwt = false

[functions.create-membership-checkout]
verify_jwt = false

[functions.create-worker]
verify_jwt = false

[functions.calendar-feed]
verify_jwt = false
