// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.25.0";

// src/lib/mcp/tools/list-bookings.ts
import { createClient } from "npm:@supabase/supabase-js@^2.90.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_bookings_default = defineTool({
  name: "list_bookings",
  title: "List my bookings",
  description: "List detailing bookings for the signed-in AV Detailing customer, most recent first.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("Maximum number of bookings to return (default 10)."),
    status: z.enum(["pending", "confirmed", "in_progress", "completed", "canceled"]).optional().describe("Optional status filter.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return {
        content: [{ type: "text", text: "Not authenticated" }],
        isError: true
      };
    }
    let query = supabaseForUser(ctx).from("bookings").select(
      "id, scheduled_date, scheduled_time, service_type, package_name, status, payment_status, total_price, vehicle_make, vehicle_model, service_address, notes"
    ).eq("user_id", ctx.getUserId()).order("scheduled_date", { ascending: false }).limit(limit ?? 10);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) {
      return {
        content: [{ type: "text", text: error.message }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { bookings: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-memberships.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.90.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.25.0";
function supabaseForUser2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_memberships_default = defineTool2({
  name: "list_memberships",
  title: "List my memberships",
  description: "List active and past AV Detailing memberships for the signed-in customer.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return {
        content: [{ type: "text", text: "Not authenticated" }],
        isError: true
      };
    }
    const { data, error } = await supabaseForUser2(ctx).from("customer_memberships").select(
      "id, status, membership_plan_id, current_period_start, current_period_end, next_service_date, created_at"
    ).eq("user_id", ctx.getUserId()).order("created_at", { ascending: false });
    if (error) {
      return {
        content: [{ type: "text", text: error.message }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { memberships: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-profile.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.90.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.25.0";
function supabaseForUser3(ctx) {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var get_profile_default = defineTool3({
  name: "get_profile",
  title: "Get my profile",
  description: "Return the signed-in customer's AV Detailing profile (name, email, phone).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return {
        content: [{ type: "text", text: "Not authenticated" }],
        isError: true
      };
    }
    const { data, error } = await supabaseForUser3(ctx).from("profiles").select("full_name, email, phone").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) {
      return {
        content: [{ type: "text", text: error.message }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? {}) }],
      structuredContent: { profile: data ?? null }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "prcrvuzncffsblsxblim";
var mcp_default = defineMcp({
  name: "av-detailing-mcp",
  title: "AV Detailing",
  version: "0.1.0",
  instructions: "Read-only tools for the signed-in AV Detailing customer. Use `list_bookings` for detailing appointments, `list_memberships` for active plans, and `get_profile` for the customer's contact info.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_bookings_default, list_memberships_default, get_profile_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.25.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
